# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5e7187a7b4aea453039394cb8cbc2bb3c79ed781a381724477901304d57fa1558913d30baff5371be275b1e179028f7852f0956b4f07f5e77fa2c6bb352ed7e2

test:
  secret_key_base: f8d08714669758c2cbb2e09f45b6acb6c958d684515ba5198fbfddc79e8890b4a2400416f3dd53ffcef6a4c414615920870583005800e1ea0be64cfb6d05cf42

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
